#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then

    echo "Create virtual environment for application"
    cd "/opt/starwit/geomapper"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt 

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/geomapper <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/geomapper
source .venv/bin/activate

python main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/geomapper    

    # link settings file from etc
    cd /opt/starwit/geomapper
    ln -sf /etc/starwit/geomapper/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start geomapper.service        
    systemctl enable geomapper.service
fi

#DEBHELPER#

exit 0